# Generated by Django 3.1.4 on 2020-12-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, default='default.png', upload_to='userpics'),
        ),
    ]
