# Generated by Django 3.1.4 on 2020-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201223_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usrnm',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
